# Generated by Django 4.2.15 on 2024-08-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_tag_alter_recipe_author_and_more'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
