# Generated by Django 3.2.16 on 2024-08-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_ingredient_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент ', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
