# Generated by Django 3.2.16 on 2024-08-05 16:43

from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=recipes.models.Base64ImageField(default=1, upload_to='recipe_images'),
            preserve_default=False,
        ),
    ]
