# Generated by Django 4.2.15 on 2024-08-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_shopcard_unique_shopcard_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-id'], 'verbose_name': 'Любимый рецепт пользователей', 'verbose_name_plural': 'Любимые рецепты пользователей'},
        ),
    ]
