# Generated by Django 4.2.15 on 2024-08-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcard',
            options={'ordering': ['-id'], 'verbose_name': 'Список покупок пользователей', 'verbose_name_plural': 'Списки покупок пользователей'},
        ),
    ]
