# Generated by Django 3.2.16 on 2024-08-06 16:32

from django.db import migrations
import recipes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=recipes.fields.Base64ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
