# Generated by Django 4.2.15 on 2024-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_customgroup_alter_user_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
    ]
