# Generated by Django 4.2.15 on 2024-08-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_tag_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
